Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"   # Ubuntu 22.04 LTS

  config.vm.network "forwarded_port", guest: 7000, host: 7000

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y openjdk-17-jdk maven
  SHELL

  config.vm.synced_folder "./app", "/home/vagrant/app"
end